# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.network :hostonly, "192.168.13.27"
  config.vm.share_folder "natura2000db", "/natura2000db", "../"

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "mapnik"
  end
end
